version: '3.8'

services:

  jupyter:
    container_name: jupyter
    image: jupyter/minimal-notebook:python-3.9.5
    working_dir: /notebooks
    volumes:
      - ./notebooks:/notebooks
      - ./training_data:/training_data
    ports:
      - 8888:8888
    depends_on:
      - es

  kibana:
    container_name: kibana
    links:
      - es:elasticsearch
    image: kibana:7.14.0
    ports:
      - 5601:5601
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: elasticsearch:9200
    depends_on:
      - es
    
  es:
    container_name: es
    image: elasticsearch:7.14.0
    ports:
      - 9200:9200
    volumes:
      - es-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms900m -Xmx900m
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

volumes:
  es-data:
